---
controller_credentials:
  - name: '{{ AAP API Cred }}'
    description: '{{ AAP API Cred }}'
    organization: Default
    credential_type: Red Hat Ansible Automation Platform
    inputs:
      host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
      password: "{{ lookup('ansible.builtin.env', 'CONTROLLER_PASSWORD') }}"
      username: "{{ lookup('ansible.builtin.env', 'CONTROLLER_USERNAME') }}"
      verify_ssl: "{{ lookup('ansible.builtin.env', 'CONTROLLER_VALIDATE_CERTS') | ansible.builtin.bool }}"
